<a href="https://colab.research.google.com/github/Roshinivemuluri/Roshini-data-analytics-training/blob/main/Crisp-framework(25-11-2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.6)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [ ]:
import opendatasets as od

In [ ]:
od.download("https://www.kaggle.com/datasets/waqi786/titanic-dataset")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: roshinivemuluri
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/waqi786/titanic-dataset
Downloading titanic-dataset.zip to ./titanic-dataset

100%|██████████| 40.6k/40.6k [00:00<00:00, 16.3MB/s]

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/titanic-dataset/Titanic.csv')

In [ ]:
data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1000 non-null   int64
 1   Pclass       1000 non-null   int64
 2   Name         1000 non-null   object
 3   Sex          1000 non-null   object
 4   Age          1000 non-null   int64
 5   SibSp        1000 non-null   int64
 6   Parch        1000 non-null   int64
 7   Ticket       1000 non-null   object
 8   Fare         1000 non-null   float64
 9   Embarked     1000 non-null   object
 10  Survived     1000 non-null   int64
dtypes: float64(1), int64(6), object(4)
memory usage: 86.1+ KB

In [ ]:
data.shape

(1000, 11)

In [ ]:
data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1

In [ ]:
data.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
995,996,2,Brittany Ward,male,69,2,3,75eb0e8f-a090-460d-a7c7-655a7b434a72,19.87,Q,1
996,997,2,Edward Stanley,female,61,4,4,e55b93ad-8976-4471-9d7f-57d1e45def26,85.35,C,0
997,998,3,Christina Johnson,male,10,4,1,d06d3943-c8b3-415e-b664-704355c9bf0f,444.22,C,0
998,999,3,Edgar Miller,male,50,3,2,0e5779ec-be1a-470f-ad83-a4c869f8d3e4,234.67,S,1
999,1000,1,Elizabeth Sanders,male,3,3,3,90a014ab-4ca1-4abd-8565-0e0bd5c97d5d,286.65,C,1

In [ ]:
data.describe()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Survived
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,1.964000,38.458000,2.032000,2.005000,247.968650,0.492000
std,288.819436,0.820596,23.103723,1.424431,1.410306,139.301211,0.500186
min,1.000000,1.000000,1.000000,0.000000,0.000000,10.020000,0.000000
25%,250.750000,1.000000,19.000000,1.000000,1.000000,126.295000,0.000000
50%,500.500000,2.000000,36.500000,2.000000,2.000000,246.500000,0.000000
75%,750.250000,3.000000,59.000000,3.000000,3.000000,365.662500,1.000000
max,1000.000000,3.000000,79.000000,4.000000,4.000000,499.780000,1.000000

In [ ]:
data.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked', 'Survived'],
      dtype='object')

In [ ]:
data.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
data.values

array([[1, 3, 'Allison Hill', ..., 144.08, 'Q', 1],
       [2, 1, 'Noah Rhodes', ..., 249.04, 'S', 0],
       [3, 3, 'Angie Henderson', ..., 50.31, 'Q', 1],
       ...,
       [998, 3, 'Christina Johnson', ..., 444.22, 'C', 0],
       [999, 3, 'Edgar Miller', ..., 234.67, 'S', 1],
       [1000, 1, 'Elizabeth Sanders', ..., 286.65, 'C', 1]], dtype=object)

In [ ]:
data.rename(columns={'old_name': 'new_name'})

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1
...,...,...,...,...,...,...,...,...,...,...,...
995,996,2,Brittany Ward,male,69,2,3,75eb0e8f-a090-460d-a7c7-655a7b434a72,19.87,Q,1
996,997,2,Edward Stanley,female,61,4,4,e55b93ad-8976-4471-9d7f-57d1e45def26,85.35,C,0
997,998,3,Christina Johnson,male,10,4,1,d06d3943-c8b3-415e-b664-704355c9bf0f,444.22,C,0
998,999,3,Edgar Miller,male,50,3,2,0e5779ec-be1a-470f-ad83-a4c869f8d3e4,234.67,S,1
999,1000,1,Elizabeth Sanders,male,3,3,3,90a014ab-4ca1-4abd-8565-0e0bd5c97d5d,286.65,C,1

In [ ]:
data.sort_values('Age')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
386,387,3,Adam Burgess,female,1,0,0,12b99a50-8cb6-41f0-a509-6396761579e7,51.22,C,1
338,339,1,Scott Thomas,male,1,0,0,c53f1db3-d275-4d43-8451-7303e94d4fbe,368.43,Q,1
288,289,2,Lisa Allen,female,1,1,2,4458b006-332c-4e0a-8e7d-a698ab95c72f,89.00,Q,0
358,359,2,Christian Leblanc,male,1,0,3,1e494952-ac5d-4e57-a3b6-64f40452f779,483.22,S,1
476,477,1,Robin Brown,male,1,4,4,8a0ea57a-9a7d-409d-a6e8-790b215d3b1f,49.80,S,0
...,...,...,...,...,...,...,...,...,...,...,...
421,422,1,Maria Jones,female,79,2,1,23ef5561-839e-4623-81d8-41d32a74b90c,279.44,C,1
780,781,1,Christine Goodwin,female,79,3,2,43d643ed-236e-4832-a7f6-a2ac5b0c4170,303.74,Q,0
213,214,1,Katherine Salas,male,79,3,2,f4acc7e2-fa57-4cea-b957-134490a4a421,67.13,S,0
701,702,3,James Watson,female,79,4,4,b0d515ab-c891-455d-94c1-76b90ac013d5,231.35,Q,0
876,877,1,Michael Miles,female,79,3,4,d6eaf269-514e-4353-af23-7c4d1e4ea133,242.79,Q,1

In [ ]:
data.drop(columns=['Age'])

,PassengerId,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1
...,...,...,...,...,...,...,...,...,...,...
995,996,2,Brittany Ward,male,2,3,75eb0e8f-a090-460d-a7c7-655a7b434a72,19.87,Q,1
996,997,2,Edward Stanley,female,4,4,e55b93ad-8976-4471-9d7f-57d1e45def26,85.35,C,0
997,998,3,Christina Johnson,male,4,1,d06d3943-c8b3-415e-b664-704355c9bf0f,444.22,C,0
998,999,3,Edgar Miller,male,3,2,0e5779ec-be1a-470f-ad83-a4c869f8d3e4,234.67,S,1
999,1000,1,Elizabeth Sanders,male,3,3,90a014ab-4ca1-4abd-8565-0e0bd5c97d5d,286.65,C,1

In [ ]:
data.fillna(4)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1
...,...,...,...,...,...,...,...,...,...,...,...
995,996,2,Brittany Ward,male,69,2,3,75eb0e8f-a090-460d-a7c7-655a7b434a72,19.87,Q,1
996,997,2,Edward Stanley,female,61,4,4,e55b93ad-8976-4471-9d7f-57d1e45def26,85.35,C,0
997,998,3,Christina Johnson,male,10,4,1,d06d3943-c8b3-415e-b664-704355c9bf0f,444.22,C,0
998,999,3,Edgar Miller,male,50,3,2,0e5779ec-be1a-470f-ad83-a4c869f8d3e4,234.67,S,1
999,1000,1,Elizabeth Sanders,male,3,3,3,90a014ab-4ca1-4abd-8565-0e0bd5c97d5d,286.65,C,1

In [ ]:
data.Fare

0      144.08
1      249.04
2       50.31
3      235.20
4      160.17
        ...
995     19.87
996     85.35
997    444.22
998    234.67
999    286.65
Name: Fare, Length: 1000, dtype: float64

In [ ]:
data.dropna()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1
...,...,...,...,...,...,...,...,...,...,...,...
995,996,2,Brittany Ward,male,69,2,3,75eb0e8f-a090-460d-a7c7-655a7b434a72,19.87,Q,1
996,997,2,Edward Stanley,female,61,4,4,e55b93ad-8976-4471-9d7f-57d1e45def26,85.35,C,0
997,998,3,Christina Johnson,male,10,4,1,d06d3943-c8b3-415e-b664-704355c9bf0f,444.22,C,0
998,999,3,Edgar Miller,male,50,3,2,0e5779ec-be1a-470f-ad83-a4c869f8d3e4,234.67,S,1
999,1000,1,Elizabeth Sanders,male,3,3,3,90a014ab-4ca1-4abd-8565-0e0bd5c97d5d,286.65,C,1

In [ ]:
data.groupby("Name")

In [ ]:
data.pivot_table(values="Age", index="Name", columns="Pclass")

Pclass               1     2     3
Name
Aaron Miller       NaN   4.0   NaN
Aaron Parker       2.0   NaN   NaN
Aaron Schroeder    NaN   NaN  68.0
Aaron Wise         3.0   NaN   NaN
Abigail Shaffer    NaN   NaN  71.0
...                ...   ...   ...
Zachary Hicks      NaN   NaN  47.0
Zachary Mendoza   68.0   NaN   NaN
Zachary Michael   35.0   NaN   NaN
Zachary Mitchell   NaN  36.0   NaN
Zachary Robinson   NaN  14.0   NaN

[995 rows x 3 columns]

In [ ]:
data.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
Survived         int64
dtype: object

In [ ]:
data.sample()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
9,10,3,Ryan Munoz,female,28,2,1,3a3e46b0-96f8-4ff7-81a7-2883f8802878,365.25,S,1

In [ ]:
data.query('Age > 17')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1
5,6,1,Connie Lawrence,male,30,2,3,907276ea-44c0-4a9a-964a-cb1f39eb038a,412.97,Q,1
...,...,...,...,...,...,...,...,...,...,...,...
991,992,3,Brian Harris,female,78,1,3,31ab0158-2cf6-473b-9500-c14707743c94,328.20,C,1
992,993,2,Michael Bowen,male,75,2,1,ec1a86d3-5683-4783-9575-9337549c9eb9,337.75,S,0
995,996,2,Brittany Ward,male,69,2,3,75eb0e8f-a090-460d-a7c7-655a7b434a72,19.87,Q,1
996,997,2,Edward Stanley,female,61,4,4,e55b93ad-8976-4471-9d7f-57d1e45def26,85.35,C,0
998,999,3,Edgar Miller,male,50,3,2,0e5779ec-be1a-470f-ad83-a4c869f8d3e4,234.67,S,1