<a href="https://colab.research.google.com/github/Roshinivemuluri/Roshini-data-analytics-training/blob/main/Index-True%2CFalse(10-12-2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv('/content/archive (5).zip')

In [6]:
data

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

# **Assignment-1**
#Task-1: -
##Reset_index where drop is False##

In [7]:
# prompt: Using dataframe data: df.reset_index(drop=False)

# Reset the index of the DataFrame, keeping the old index as a column.
data.reset_index(drop=False)

,index,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...,...
995,995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120


#Summary#
## The method df.reset_index(drop=False) is used in pandas to reset the index of a DataFrame. Let me break it down:

## Purpose
## Reset the Index:

## If a DataFrame has a custom index (e.g., after filtering, slicing, or setting an index), this method will reset it back to the default integer-based index (0, 1, 2, ...).
## Retain the Old Index:

# By default, reset_index(drop=False) keeps the old index as a new column in the DataFrame. This is helpful if you want to preserve the original index values for reference.
## Parameters
## drop (default is False):
## If False (as in df.reset_index(drop=False)), the old index is added as a column in the DataFrame.
## If True, the old index is discarded completely.

#summary#

### **When to Use `df.reset_index(drop=False)`**
1. ## Restore Default Index: Use when your DataFrame has a custom or non-standard index (e.g., after slicing, grouping, or setting an index) and you want to revert it to the default integer-based index (0, 1, 2, ...).
   
2. ## Preserve the Original Index: Use when the original index contains meaningful data (e.g., dates, labels) and you want to keep it as a new column in the DataFrame.

3. ## Before Export or Merging: Useful when preparing the DataFrame for tasks like exporting to a file or merging with another DataFrame that requires a standard index.

4. ## For Reference: Keeps the old index accessible for tracking or debugging without losing it.

## If you don’t need the old index, set `drop=True` to discard it entirely.

#Task-2: -
##Reset_index where drop is **True**

In [8]:
# prompt: df.reset_index(drop=True)

# Reset the index of the DataFrame, dropping the old index.
data.reset_index(drop=True)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120


# Summary Why Use df.reset_index(drop=True)
##Remove the Existing Index: It discards the current index and assigns a default integer index (0, 1, 2, ...).

##Avoid Adding the Old Index as a Column: Unlike drop=False, this option does not retain the old index as a new column, simplifying the DataFrame.

##Clean DataFrame: Creates a fresh index after operations like filtering, merging, or shuffling, where the old index may no longer be meaningful.

##Prepare for Export or Re-indexing: Ensures the DataFrame has a clean, sequential index for tasks like exporting data or aligning with another DataFrame.

##When to Use
#Old Index is Irrelevant: When the current index no longer has meaningful or unique values.
##Resetting After Modifications: After operations like filtering or concatenation where the index is inconsistent or non-sequential.
##Data Cleaning: To simplify and standardize the DataFrame before further analysis or sharing.


# Summary When to Use df.reset_index(drop=True)
##Discard the Current Index: Use it when the existing index is irrelevant or meaningless, such as after filtering, grouping, or shuffling rows.

##Avoid Keeping the Old Index: Choose drop=True when you don’t need the old index retained as a new column, keeping the DataFrame simple and clean.

##Standardize the Index: After operations like concatenation or reordering, where the index may be non-sequential or not useful anymore.

##Prepare for Export or Further Processing: Ensures a clean, default integer index (0, 1, 2, ...) before saving to a file or sharing for analysis.

#Key Scenarios
##Post-Slicing or Filtering: If the DataFrame has gaps or inconsistencies in the index.
##After Combining Datasets: When indices from merged or concatenated DataFrames don’t align.
##Data Cleaning: To refresh the index and make the DataFrame easier to work with.

# **Assignment-2**
##Task-1: -
##Converting the modified Data set to CSV with **False **

In [9]:
data.to_csv('output.csv', index=False)

#SUMMARY: -
##index=False prevents writing row indices to the CSV

#Task-2: -
##Converting the modified Data set to CSV with **True**

In [10]:
data.to_csv('output.csv', index=True)

#SUMMARY: -
##The line Set.to_csv('output.csv', index=True) saves the DataFrame Set to a CSV file named 'output.csv'.
The key part is index=True. This tells the to_csv function to include the DataFrame's index in the output CSV file.
If index=True (or if you omit the index parameter entirely, as it defaults to True):
The index (the row labels) of your DataFrame will be written as the first column in the CSV.
has context menu